export const actions = {
  ADD_TODO: "ADD_TODO",
  EDIT_TODO: "EDIT_TODO",
  DELETE_TODO: "DELETE_TODO",
  COMPLETE_TODO: "COMPLETE_TODO",
  RESTORE_TODO: "RESTORE_TODO",
  COMPLETE_ALL: "COMPLETE_ALL",
  RESTORE_ALL: "RESTORE_ALL",
  DELETE_ALL: "DELETE_ALL",
};
